# Generated by Django 6.0 on 2025-12-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(help_text='Enter the ingredients, separated by a comma', max_length=225)),
                ('cooking_time', models.IntegerField(help_text='Cooking time in minutes')),
            ],
        ),
    ]
